#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 100 in list format, replacing multiples of 3 with "Fizz",
# multiples of 5 with "Buzz", multiples of both 3 and 5 with "FizzBuzz", and printing the number
# for all other cases.
 
for num in {1..100}
do
  if (( num % 3 == 0 && num % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
done

