#!/usr/bin/env bash

# Script: display-passwd-info.sh
# Description: Displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

# Define the file to be displayed.


while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
