#!/usr/bin/env bash

# Script: display-passwd-info.sh
# Description: Displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

# Define the file to be displayed.
myfile="/etc/passwd"

while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$myfile"

