#!/usr/bin/env bash
# A script which display "Best School" 10 times then "hi" after the 9th using both the while and if

i=1

while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
