#!/usr/bin/env bash

# This script loops through numbers 1 to 10 using a while loop and prints "Best School" for each number, except 4 (which prints "bad luck") and 8 (which prints "good luck").
 
i=1

while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done

