#!/usr/bin/env bash

# This script loops through numbers 1 to 10 using a while loop and prints "Best School" for each number, except 4 (which prints "bad luck") 

index=0

while [ $index -lt 10 ]
do
  if [ $index -eq 3 ]
  then
    echo "bad luck"
  elif [ $index -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( index++ ))
done
