#!/usr/bin/env bash
# A Bash script that displays the content of the current directory in list format.
# For each item in the list, it only displays the part of the name after the first dash.
# The script first stores the output of 'ls' in a variable called 'mylist', and then
# uses a 'for' loop to iterate over each item in the list. For each item, it uses the 'cut'
# command to extract the part of the name after the first dash and prints it to the console.

mylist=$(ls)

for i in $mylist; do
  echo "$i" | cut -d '-' -f2
done

