#!/usr/bin/env bash
# A Bash script that displays information about the file 'school'.
# If the file exists, it checks whether it's empty or not, and whether it's a regular file or not.
# The script uses the '-e' flag to check if the file exists, the '-s' flag to check if it's empty,
# and the '-f' flag to check if it's a regular file. If the file doesn't exist, the script prints
# a message saying so.

if [ -e "school" ]
then
  echo "school file exists"
  if [ -s "school" ]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi

  if [ -f "school" ]
  then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi

